// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rotmokapuyhivtvdigmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdG1va2FwdXloaXZ0dmRpZ21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1ODUwODAsImV4cCI6MjA1MDE2MTA4MH0.SNp7vy1ZMBbQIVq-V5iObQ2KvHyiE36T6CO8FqJX5Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);